#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import sys
from typing import Any


def py_name(c_name: str) -> str:
    return c_name.removeprefix("pcap_")


def infer_kind(func: dict[str, Any]) -> str:
    args = func.get("args", [])

    if len(args) == 0:
        return "NOARGS"

    return "FAST_KEYWORDS"


def emit_x(func: dict[str, Any]) -> str:
    c_name = func["name"]
    name = py_name(c_name)
    kind = infer_kind(func)
    doc = f"{c_name} wrapper"

    return f'X(0, {kind}, {name}, "{doc}")'


def load_functions_from_stdin() -> list[dict[str, Any]]:
    data = json.load(sys.stdin)

    if isinstance(data, list):
        return data

    if isinstance(data, dict):
        if isinstance(data.get("functions"), list):
            return data["functions"]

    raise SystemExit("expected JSON array from stdin")


def load_functions_from_stdin() -> list[dict[str, Any]]:
    raw = sys.stdin.read()

    if not raw.strip():
        raise SystemExit("expected JSON from stdin")

    data = json.loads(raw)

    if isinstance(data, list):
        return data

    if isinstance(data, dict) and isinstance(data.get("functions"), list):
        return data["functions"]

    raise SystemExit("expected JSON array from stdin")


def main() -> None:
    funcs = load_functions_from_stdin()

    print("/* generated by gen-function-list.py */")

    for func in funcs:
        if "name" not in func:
            continue

        print(emit_x(func))


if __name__ == "__main__":
    main()
