name: Lint

on:
  pull_request:
  push:
    branches: [main]


jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [nix, ruff, clang, readme-functions]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-nix

      - run: nix develop -c just lint-${{ matrix.target }}
